## Purpose
This will be the final document we submit for evaluation

## Research questions:
1. Please combine RQ1 and RQ3 to something like: What are general dependencies between weather features over different time scales? (not only correlation)
2. RQ2: How do Europe and North America compare regarding weather season attributes (as e.g. mean temperatures, total precipitation, etc.)
3. New RQ3: Since you brought it up in the last paragraph;), wouldn't it be interesting to investigate on how key weather features changed over the last 50-100 years for e.g Zurich and Seattle?

In [7]:
import pandas as pd

In [6]:
# Create the dataset by calling the api
# %run get_data.py

In [8]:
df = pd.read_csv('Data/start.csv')

In [10]:
df.head()

,date,weather_code,temperature_2m_max,temperature_2m_min,temperature_2m_mean,apparent_temperature_max,apparent_temperature_min,apparent_temperature_mean,sunrise,sunset,...,precipitation_sum,rain_sum,snowfall_sum,precipitation_hours,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant,shortwave_radiation_sum,et0_fao_evapotranspiration,City
0,1939-12-31 23:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,Zurich
1,1940-01-01 23:00:00+00:00,1.0,-7.330999,-17.230999,-12.360166,-12.075075,-21.555338,-17.330599,0,0,...,0.0,0.0,0.0,0.0,12.496718,30.599998,37.225502,6.15,0.396700,Zurich
2,1940-01-02 23:00:00+00:00,3.0,-1.681000,-17.781000,-10.441416,-5.699105,-21.838583,-14.508773,0,0,...,0.0,0.0,0.0,0.0,6.608722,19.440000,30.379032,5.74,0.396855,Zurich
3,1940-01-03 23:00:00+00:00,3.0,1.219000,-6.631000,-1.766416,-2.445471,-10.648111,-5.441375,0,0,...,0.0,0.0,0.0,0.0,7.289445,19.440000,31.273705,3.16,0.386221,Zurich
4,1940-01-04 23:00:00+00:00,3.0,1.219000,-5.681000,-2.364334,-2.262167,-9.751736,-6.058429,0,0,...,0.0,0.0,0.0,0.0,6.109403,15.840000,36.539864,5.37,0.495947,Zurich